add : ログイン時パスワードを忘れた時の機能を追加
ih14c-13-14/artist-backend pull request #116
Opened 2023-07-10 03:28 UTC by 4s2r9

# やったこと
機能実装

# やらないこと
メール送信機能

# レビュー依頼前にやること

- [x] セルフレビューを行なった。
- [x] スペルミスがないことを確認した。
- [ ] `yarn lint`
- [ ] `yarn test`
- [ ] `yarn build`

2023-07-10 03:45 UTC, na2na-p commented
@4s2r9 `yarn fmt:fix && yarn lint:fix`して、出てきた差分で1コミット積んだ方がよさそう

2023-07-10 07:22 UTC, ryota658 commented on src/users/users.controller.ts
> +import { PasswordChange } from './dto/password-chenge';
```diff
- import { PasswordChange } from './dto/password-chenge';
+ import { PasswordChange } from './dto/password-change';
```

ファイル名タイプミスしてる

2023-07-10 12:52 UTC, 4s2r9 commented on src/users/users.controller.ts
> +import { PasswordChange } from './dto/password-chenge';
sory...

2023-07-10 13:11 UTC, ryota658 commented on src/users/users.service.ts
> +		const HashPassword = await bcrypt.hash(NewPassword.password, salt);
```suggestion
		const hashPassword = await bcrypt.hash(NewPassword.password, salt);
```
先頭小文字にしてください。

2023-07-10 15:20 UTC, ryota658 approved these changes
確認しました。

2023-07-10 16:23 UTC, Issiki0416 approved these changes
ドラフトだった
確認しました

2023-07-11 02:59 UTC, na2na-p requested changes

2023-07-11 02:59 UTC, na2na-p commented on src/users/users.service.ts
> +	});
かっこが足りてないかも
```suggestion

	async getUserById(user_id: string): Promise<Users> {
		return await this.prismaService.users.findUnique({
			where: {
				id: user_id,
			},
		});
	}
}
```

2023-07-11 03:51 UTC, 4s2r9 commented on src/users/users.service.ts
> +	});
ん?俺このusers.service知らないよ

2023-07-11 04:17 UTC, Issiki0416 approved these changes
いける

2023-07-11 06:15 UTC, na2na-p approved these changes
ほか二人がApprove出していて、かつCI通過するのでヨシ！

2023-07-11 06:15 UTC, merged