Chore/jwt token controller
ih14c-13-14/artist-backend pull request #171
Opened 2023-07-14 14:02 UTC by Issiki0416

# やったこと
1.  JWTのGuardを設定できなかったのでできるように
2.  expを1hにする

# やらないこと
- テスト

# レビュー依頼前にやること

- [x] セルフレビューを行なった。
- [x] スペルミスがないことを確認した。
- [x] `yarn lint`
- [ ] `yarn test`
- [x] `yarn build`
![image](https://github.com/ih14c-13-14/artist-backend/assets/96870513/6828edb7-0947-4a72-a13b-5f19ae048e2b)

# 動作確認
1. JWTのGuardを設定できなかったのでできるように
### Tokenが間違ってるとき
![image](https://github.com/ih14c-13-14/artist-backend/assets/96870513/348c5ed9-b5a7-4af6-bbdc-ee83c8b18407)

### Tokenがないとき
<img width="1098" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/96870513/7814f8cc-c0cc-4489-82b8-32a88b0e48d0">

### Tokenがあるとき
<img width="1092" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/96870513/7964311f-01d0-4092-850d-cb6db7ad1f51">

2.  expを1hにする
<img width="500" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/96870513/514e5939-f203-4ffe-8f82-564f2914b059">

2023-07-14 15:43 UTC, na2na-p reviewed
酒はいっててスマホから見てるので細かいところは@ryota658 先生お願いします

2023-07-14 15:43 UTC, na2na-p commented on src/auth/auth.controller.ts
> +	 * @returns string   JWTトークン
ほんとうにプリミティブ返してる？

2023-07-15 01:15 UTC, na2na-p requested changes

2023-07-15 01:15 UTC, na2na-p commented on src/auth/auth.controller.ts
> +	 * @returns string   JWTトークン
改めて見たけどJSDocとしては不適かも

https://www.typescriptlang.org/ja/docs/handbook/jsdoc-supported-types.html#param%E3%81%A8returns

2023-07-15 01:15 UTC, na2na-p commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
[質問]
TOKENSっていうレイヤーに隠蔽したのはいいアイディアだと思ったけどここで書き直した理由は？

2023-07-15 01:15 UTC, na2na-p commented on src/auth/auth.service.ts
> +			email: user.email,
[質問]
バックエンド的にはemailはsubから引くことができると思うけどここに追加って必要？
フロントエンド的にもemailをトークンから引っ張り出すユースケースはないです

2023-07-15 01:15 UTC, na2na-p commented on src/auth/strategies/jwt.strategy.ts
> +		const user = await this.authService.getUser(email);
[提案]
ここsubに格納されるuser_idを使うことはできませんか？

2023-07-15 04:44 UTC, Issiki0416 commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
それが全ての元凶。。。設定が反映されてないんだよね
`process.env.JWT_ACCESS_TOKEN_EXPIRES_IN,`でもだめだったのでそのままぶっこんだ

2023-07-15 04:45 UTC, Issiki0416 commented on src/auth/auth.controller.ts
> +	 * @returns string   JWTトークン
そのままの方が良い？
` @returns {object}   JWTトークン`

2023-07-15 04:51 UTC, na2na-p commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
process.env経由で取ってるのに型がstring | undefinedのユニオンにならないのがまず違和感あるかも

2023-07-15 05:25 UTC, Issiki0416 commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
`expiresIn: Number(process.env.JWT_ACCESS_TOKEN_EXPIRES_IN), ` みたいに`Number`でキャストすると通った

2023-07-15 05:38 UTC, na2na-p commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
型チェックさん……

2023-07-15 06:59 UTC, na2na-p commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
`Number(process.env.JWT_ACCESS_TOKEN_EXPIRES_IN)`とする場合、`NaN`になっていないかは確認しないとダメです。

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAygFQEoEkByBxGBeGAiAQzwG4AoUSWNAVQFkAhAUSRxgEYzzwIQAbAUwB0vEAHMAFGgCuAWwBG-AE7jEqTAEp1ZCjwHCxk2QuU0GzTZx18hIiQEsIaAmkPylK5OgyatXSNf17R2dXY0k6JiQfMiA

<img width="918" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/49822810/f10212da-0be1-4c23-8cae-560234fdb79e">

2023-07-15 07:02 UTC, na2na-p commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
NaNもnumber型で型チェック通過するので

<img width="843" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/49822810/51e45301-4d01-42ad-aa9d-f663415b582f">

2023-07-15 16:16 UTC, Issiki0416 commented on src/auth/auth.service.ts
> +			email: user.email,
ないので消しました

2023-07-15 16:16 UTC, Issiki0416 commented on src/auth/strategies/jwt.strategy.ts
> +		const user = await this.authService.getUser(email);
user_idで対応

2023-07-15 16:16 UTC, Issiki0416 commented on src/auth/auth.module.ts
> +				expiresIn: 3600,
configに処理を書いてそれを読み込ませる形に変えました

2023-07-15 17:42 UTC, na2na-p requested changes
NestJSの扱ってるDI周りはよくわからんので触れてませんが数点お願いします

2023-07-15 17:42 UTC, na2na-p commented on src/auth/auth.controller.ts
> +	 * @returns {Promise<{ access_token: string }>} - JWTトークン
よさそう

2023-07-15 17:42 UTC, na2na-p commented on src/config/index.ts
> +	? ''
```suggestion
const ACCESS_EXPIRES_IN: number = isNaN(Number(process.env.JWT_ACCESS_TOKEN_EXPIRES_IN))
	? 3600
```

みたいにしないとダメそう。もともとnumber型が入ってほしい箇所に空文字(string)詰めちゃってると思う

2023-07-15 17:42 UTC, na2na-p commented on src/config/index.ts
>  export const TOKENS = {
[対応は任意, 提案]
TOKENSに対して想定されうる型を作っておいて、satisfiesで制約かけたら↑の事故に気づけそう

2023-07-15 17:42 UTC, na2na-p commented on src/auth/strategies/jwt.strategy.ts
>  	async validate(payload: JwtPayload): Promise<PasswordOmitUsers> {
```suggestion
	async validate({ sub }: JwtPayload): Promise<PasswordOmitUsers> {
```

として

2023-07-15 17:42 UTC, na2na-p commented on src/auth/strategies/jwt.strategy.ts
> +		const { sub } = payload;
```suggestion
```

この行削除するとすっきりしそう。もし仮にpayload全部必要なときあるなら無視で大丈夫です

2023-07-15 17:42 UTC, na2na-p commented on src/config/index.ts
>  export const TOKENS = {
```suggestion
export const CONFIGS = {
```

こう？

2023-07-15 17:42 UTC, na2na-p commented on src/auth/strategies/jwt.strategy.ts
> +			secretOrKey: process.env.JWT_ACCESS_TOKEN_SECRET,
ここは定数のレイヤーに戻して大丈夫そう？(命名は現状の実装ベースで例示します

```suggestion
			secretOrKey: TOKENS.JWT_ACCESS_TOKEN_SECRET,
```

2023-07-15 17:42 UTC, na2na-p commented on src/auth/auth.module.ts
> +			secret: process.env.JWT_ACCESS_TOKEN_SECRET,
ここも？

```suggestion
			secret: TOKENS.JWT_ACCESS_TOKEN_SECRET,
```

2023-07-15 17:44 UTC, na2na-p commented on src/auth/strategies/jwt.strategy.ts
>  	async validate(payload: JwtPayload): Promise<PasswordOmitUsers> {
もっと言うと

```suggestion
	async validate({ sub: userId }: JwtPayload): Promise<PasswordOmitUsers> {
```

みたいにすると初見でもわかりやすいかも

2023-07-15 19:19 UTC, Issiki0416 commented on src/auth/strategies/jwt.strategy.ts
> +			secretOrKey: process.env.JWT_ACCESS_TOKEN_SECRET,
戻した！

2023-07-15 23:54 UTC, na2na-p requested changes
1点お願いします！

2023-07-15 23:54 UTC, na2na-p commented on src/config/types/index.d.ts
> +export type CONFIGS_TYPE = {
アンビエント宣言使わないのでただのtypes.tsにしてください。
`*.d.ts`は、型定義のないライブラリに対して型定義を提供する場合に使います。
`node_modules/@types`の中を見るとわかりやすいかも？

https://nishinatoshiharu.com/overview-declare/

2023-07-16 02:51 UTC, na2na-p reviewed
ナイスです！LGTM！あとは @ryota658 先生のApproveもらってください！

2023-07-16 02:54 UTC, ryota658 approved these changes

2023-07-16 02:56 UTC, na2na-p approved these changes

2023-07-16 03:04 UTC, merged