prismaのセッティング
ih14c-13-14/artist-backend pull request #4
Opened 2023-06-03 16:17 UTC by Issiki0416

# やったこと
prisma-clientとかの設定

# やらないこと

2023-06-03 20:12 UTC, na2na-p requested changes
- 機密ファイルの混入
- MySQL用の設定に置換
- Linterコケてる

2023-06-03 20:12 UTC, na2na-p commented on .env
> +# Environment variables declared in this file are automatically made available to Prisma.
今回はサンプルそのままだからまだマシだけどヤバです。いい機会なので、別で対応方法送るのでやってみましょう

2023-06-03 20:41 UTC, na2na-p commented on prisma/schema.prisma
> +  provider = "postgresql"
ついでにMySQL用に直しておきましょうか

2023-06-03 20:41 UTC, na2na-p commented on .env
先にDiscordで送った対応してから、`.env.example`としてコミットしましょう。

2023-06-03 20:41 UTC, na2na-p commented on .env
> +DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"
どうせ後で書き換えるとはいえMySQL使うならついでに書き換えちゃいましょう
ファイルの末尾に改行あるといいです。editorconfig入れとくとその辺勝手にやってくれてお得
```suggestion
DATABASE_URL = "mysql://johndoe:randompassword@localhost:3306/mydb"

```

2023-06-03 20:43 UTC, na2na-p commented on .env
> +DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"
末尾改行の設定してる箇所は以下です

https://github.com/ih14c-13-14/artist-backend/blob/5cded557b3b0d2cd81400e09596e33a3fae3d5aa/.editorconfig#L6

2023-06-03 21:24 UTC, na2na-p commented on src/app.module.ts
レビュー依頼前に
```
yarn lint --fix
```

して自動修正だけで1コミット作ってください

2023-06-03 23:16 UTC, ryota658 approved these changes

2023-06-03 23:19 UTC, ryota658 submitted a review, later dismissed

2023-06-04 02:49 UTC, Issiki0416 commented on prisma/schema.prisma
> +  provider = "postgresql"
mysql変更しました

2023-06-05 07:20 UTC, na2na-p commented on src/app.module.ts
#5 でやっちゃう

2023-06-05 09:27 UTC, na2na-p approved these changes
LGTM,お疲れ様でした

2023-06-05 09:27 UTC, merged